name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: ['9.0', '9.2']
	cabal: ['3.4', '3.6']
    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version:   ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - name: Update cabal package database
      run: |
        cabal update
        cabal freeze
    - uses: actions/cache@v2
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-
    - name: Build
      run: |
        cabal build --disable-tests --disable-benchmarks all
    - name: Test
      run: |
        cabal build --enable-tests --disable-benchmarks all
        cabal test spec
    - name: Haddock
      run: |
        cabal haddock
    - name: SDist
      run: |
        cabal sdist all
